### ISSUE TITLE
Use configuration from FireStore

### ISSUE THREAD

**Issue by gorandalum** [AtB-AS/mittatb-app#2475] opened 2022-04-05 10:32 UTC
### Origin
We have a collection called `configuration` in `Firestore`. The values stored here should be made available in the `configuration context` in the app. The app as of now uses `remoteConfig` for some of these values and should be refactored to use Firestore instead.

The buttons for payment should be using values from firestore

in issue #2430 we moved and refactored to use the values in `configuration / referenceData`. This issue will move and refactor in the values in configuration/other and configuration/paymentTypes.

- [x] fetch firestore documents from firestore
   - [x] Update the default json-files with fresh data from production values in firestore 
   - [x] Json-parse the data and cast them to the correct types
- [x] make the data available in the firestoreConfigurationContext
- [x] Refactor to use values from firestore instead of remoteconfig
  - [x] delete corresponding remote config values and code
  - [x] make use of the firestore values
- [x] Ensure the Payment buttons use values from paymentTypes from Firestore
- 
 

![Screenshot 2022-04-05 at 12 26 29](https://user-images.githubusercontent.com/675421/161735274-d527f1e8-de49-49a3-b1d2-da1ba1869093.png)

**Comment by jorelosorio** [comment] 2022-04-20 09:20
As a track note: The build failed the first time when the PR was merged, with a possible issue fetching Mapbox libraries for Android, but after a second try the next day it worked. We think that the root cause could be that the server was not reached due to a down during that moment. We are aware of this and will keep monitoring for further issues related.

**Comment by jorelosorio** [comment] 2022-04-20 13:52
@tormoseng Good catch, I new PR is made fixing this at https://github.com/AtB-AS/mittatb-app/pull/2534

**Comment by tormoseng** [comment] 2022-04-22 12:03
Re-testet OK

**Closed by tormoseng** 2022-04-22 12:03 UTC
Labels: :wrench: Forvaltning, :shirt:  S, :iphone: 1.18
